version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          - BUNDLER_VERSION: 2.1.4
      - image: circleci/mysql:5.6
    working_directory: ~/tensakun

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-tensakun-{{ checksum "Gemfile.lock" }}
        - v1-tensakun-

    - run:
        name: install dependencies
        command: |
          gem install bundler -v 2.1.4
          bundle install

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-tensakun-{{ checksum "Gemfile.lock" }}

    - run: mv ./config/database.yml.ci ./config/database.yml

    - run:
        name: databaseSet
        command: |
           bundle exec rake db:create
           bundle exec rake db:schema:load

    - run:
        name: execute rspec
        command: bundle exec rspec
    - store_test_results:
        path: /tmp/test-results
