version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    working_directory: ~/tensakun
    steps:
      - checkout
      - run:
          name: bundler install
          command: |
            gem install bundler
            bundle-install
